dist: bionic
services:
- xvfb

language: node_js
node_js:
- 12

os:
- linux
addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script:
      - npm run test:coverage
      - npm run report-coverage
    - stage: build & publish http-load
      script:
      - npm run build:http-load
      - npm run publish:http-load
      if: branch = master
    - stage: build & publish demo-app
      script:
      - npm run build:demo-app
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/demo-app
      if: branch = master
