dist: bionic
services:
- xvfb

language: node_js
node_js:
- 12

os:
- linux
addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script:
      - npm run test:coverage
      - npm run report-coverage
    - stage: build & publish
      script:
      - npm run build
      - npm run publish
      if: branch = master
